services:
  db:
    image: pgvector/pgvector:0.8.2-pg17
    container_name: whichmovie-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: whichmovie123!
      POSTGRES_DB: whichmovie
    ports:
      - "15432:5432"
    volumes:
      - whichmovie_pgdata:/var/lib/postgresql/data

volumes:
  whichmovie_pgdata: